### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by evewurtele** [zbwrnz/metaoku#1]
a couple things.

plots are very slow and hard to tell is they are done or not.

I dont seem to get what I ask for in the plots.   I dont seem to be able to use colors, or create the axes that I ask for, and sometimes it seems plot 

maybe try out sandbox using the actual Kevin .cvs file.

**Comment by evewurtele** [comment]
all "communities" collumn from Kevin should be same data type (in this case, "categorical"

**Comment by evewurtele** [comment]
the "regulon number" column from Kevin should be same data type (in this case, "categorical"

**Comment by evewurtele** [comment]
the wordplot seems to work in "view" but not in "plot"

**Comment by evewurtele** [comment]
feature request- user can remove selected words from "word cloud'.  e.g. "protein"  or "gene"

**Comment by arendsee** [comment]
There isn't much I can do about plot speed; it is dependent on the plotting function implementations (ggplot and plotly) and on the shinyapps.io hardware.

I've reconfigured the sandbox instance to allow 100 levels in a categorical variable. So it should now behave the way you want. Ultimately, I should allow the user to set this dynamically, but it will require some reworking of the data structures.

I've added a plotly interface to the plots metaoku generates. Plotly is very good about customizable and interactive graphics, so I am working on delegating as much as possible to them. Then metaoku can focus more on data sharing, documentation, typing.

Removing words from the wordcloud should be possible. I'll look into it.

**Comment by evewurtele** [comment]
:)

Eve Syrkin Wurtele, Professor     515-708-3232 (cell)  538 Science II,
Iowa State Univ.  homepage
http://www.gdcb.iastate.edu/faculty-and-research/faculty/eve-syrkin-wurtele/
Meta!Blast computer game http://metablast.org/    PMR Systems Biology
Resource http://www.metnetdb.org/PMR/   Publications
http://www.ncbi.nlm.nih.gov/sites/myncbi/collections/public/1jMsIEbfU0gcCYtuh_aBiUdAs/?sort=date&direction=descending
